---
# defaults file for odoo_role
# defaults file for odoo_role
odoo_image: odoo:17.0
odoo_name: odoo_web
database_name: db-odoo
database_username: odoo
database_password: myodoo
odoo_host_port: 8069
odoo-web-data:  odoo-web-data
odoo-db-data: odoo-db-data
database_image: postgres:15